version: "3.7"
  
services:
  traefik:
    image: traefik:2.1
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic-conf.yml:/dynamic-conf.yml:ro
      - ./.htpasswd:/.htpasswd:ro
      - traefik-etc:/usr/local/etc
        #      - /etc/ssl/${BASE_DOMAIN}:/etc/ssl/base-domain:ro
        #      - /etc/ssl/intern.schmitt-aufzuege.com:/etc/ssl/intern.schmitt-aufzuege.com:ro
networks:
  proxy:
    name: ${DOCKER_NETWORK_NAME}
    external: true

volumes:
  traefik-etc:
    name: traefik-etc
