global:
  checkNewVersion: false
  sendAnonymousUsage: false
serversTransport:
  insecureSkipVerify: true
entryPoints:
  http:
    address: :80
  https:
    address: :443
  traefik:
    address: :8080
providers:
  providersThrottleDuration: 2s
  file:
    filename: "/dynamic-conf.yml"
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false
api:
  insecure: true 
  dashboard: true
log: {}
accessLog: {}
certificatesResolvers:
  default:
    acme:
      email: masteryoda@gmx.de
      storage: acme.json
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory #staging only, uncomment for live sites
      httpChallenge:
        entryPoint: http
